### ISSUE TITLE
OnJoin error for systemless player.

### ISSUE THREAD

**Issue by Kurumi78** [Kurumi78/SystemSwap#1]
Plugin errors due to trying to innit data for a player that doesnt exist.
`[09:01:56 WARN]: [SystemSwap] Plugin SystemSwap vprealpha-4 generated an exception while executing task 10
java.lang.NullPointerException: Cannot invoke "String.length()" because "name" is null
        at java.base/java.util.UUID.fromString(UUID.java:239) ~[?:?]
        at SystemSwap-prealpha-4.jar/com.gmail.kurumitk78.systemswap.SystemSwap.initPlayerSystem(SystemSwap.java:79) ~[SystemSwap-prealpha-4.jar:?]
        at SystemSwap-prealpha-4.jar/com.gmail.kurumitk78.systemswap.listeners.PlayerJoinListener$1.run(PlayerJoinListener.java:25) ~[SystemSwap-prealpha-4.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Kurumi78** [comment]
Theoretically fixed by this [commit](https://github.com/Kurumi78/SystemSwap/commit/b9e2472a66966f2dabaee10bfcdf6266d6af81d3)

**Comment by Kurumi78** [comment]
Waiting for conformation from a tester before closing.
