### ISSUE TITLE
Error on chat

### ISSUE THREAD

**Issue by Kurumi78** [Kurumi78/SystemSwap#2]
Honestly, Ive no clue at time of writing what the issue is. 
`[09:05:08 INFO]: KTrain5369 issued server command: /system create KTools
[09:05:18 INFO]: KTrain5369 issued server command: /alt
[09:05:25 INFO]: KTrain5369 issued server command: /alters
[09:05:44 INFO]: KTrain5369 issued server command: /alters create KTrain:D
[09:06:07 INFO]: KTrain5369 issued server command: /alters create KTools:D
op Kurumi78
[09:07:06 INFO]: Made Kurumi78 a server operator
gamemode creative KTrain5369
[09:08:20 INFO]: Set KTrain5369's game mode to Creative Mode
[09:09:21 INFO]: KTrain5369 issued server command: /systemswap:alters
[09:10:23 INFO]: KTrain5369 issued server command: /alters set
[09:10:41 INFO]: KTrain5369 issued server command: /alters set KTrain:D proxytag KTrain
[09:10:44 ERROR]: Could not pass event AsyncPlayerChatEvent to SystemSwap vprealpha-4
java.lang.StringIndexOutOfBoundsException: Range [0, 6) out of bounds for length 2
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2834) ~[?:?]
        at SystemSwap-prealpha-4.jar/com.gmail.kurumitk78.systemswap.System.lambda$containsProxyTag$2(System.java:112) ~[SystemSwap-prealpha-4.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at SystemSwap-prealpha-4.jar/com.gmail.kurumitk78.systemswap.System.containsProxyTag(System.java:109) ~[SystemSwap-prealpha-4.jar:?]
        at SystemSwap-prealpha-4.jar/com.gmail.kurumitk78.systemswap.listeners.chatListener.checkForFrontChanges(chatListener.java:30) ~[SystemSwap-prealpha-4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-150-e61b73f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2388) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2504) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$9(ServerGamePacketListenerImpl.java:2160) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Kurumi78** [comment]
Issue happened when a proxytag is longer then the length of the text.

Theoretically fixed in [this commit](https://github.com/Kurumi78/SystemSwap/commit/78964a0aa96d4b5897e56852f5025dd96e1dd3fb)

Waiting to close till a tester can confirm.
